In [1]:
import duckdb

In [2]:
# Database connection
con = duckdb.connect("retail_db.duckdb")

### Data Overview

In [4]:
# list of Fact Tables:
# 1. fact_sales
# 2. fact_purchage
# 3. fact_begin_to_end_inventory
# 4. fact_end_to_begin_inventory


# list of Dimension Tables:
# 1. dim_brand_purchase_sales
# 2. dim_vendor
# 3. dim_store
# 4. dim_inventory
# 5. dim_brand_inventory
# 6. dim_date

In [5]:
# Row counts
all_rows_count = """
select 'fact_sales' as table, count(*) from fact_sales
union all
select 'fact_purchage' as table, count(*) from fact_purchage
union all
select 'fact_begin_to_end_inventory' as table, count(*) from fact_begin_to_end_inventory
union all
select 'fact_end_to_begin_inventory' as table, count(*) from fact_end_to_begin_inventory;
"""

con.execute(all_rows_count).df()

                         table  count_star()
0                   fact_sales      12825363
1                fact_purchage       2372474
2  fact_begin_to_end_inventory        206529
3  fact_end_to_begin_inventory        224489

In [ ]:
# Null check - Fact_Sales
null_check_sales = """
select 
    sum(case when Brand_ID is null then 1 else 0 end) as null_brand,
    sum(case when vendor_id is null then 1 else 0 end) as null_vendor,
    sum(case when store_id is null then 1 else 0 end) as null_store,
    sum(case when date_id is null then 1 else 0 end) as null_date,
    sum(case when SalesQuantity is null then 1 else 0 end) as null_sales_qty,
    sum(case when SalesDollars is null then 1 else 0 end) as null_sales_doller,
    sum(case when SalesPrice is null then 1 else 0 end) as null_sales_proce
from fact_sales;
"""

con.execute(null_check_sales).df()

,null_brand,null_vendor,null_store,null_date,null_sales_qty,null_sales_doller,null_sales_proce
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
# Null check - Fact_Purchase
null_check_purchase = """
select 
    sum(case when inv_date_id is null then 1 else 0 end) as null_inv_date,
    sum(case when pay_date_id is null then 1 else 0 end) as null_pay_date,
    sum(case when inventory_id is null then 1 else 0 end) as null_inventory,
    sum(case when PurchasePrice is null then 1 else 0 end) as null_purchase_price,
    sum(case when Quantity is null then 1 else 0 end) as null_quentity,
    sum(case when Dollars is null then 1 else 0 end) as null_doller
from fact_purchage;
"""
con.execute(null_check_purchase).df()

,null_inv_date,null_pay_date,null_inventory,null_purchase_price,null_quentity,null_doller
0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
con.execute('select * from fact_purchage limit 3').fetch_df()